# Generated by Django 5.1.7 on 2025-11-06 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'Standard User'), ('guide', 'Guide/Mentor'), ('admin', 'Administrator')], default='user', max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, help_text="User's age (optional)", null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth (optional)", null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Tell us a bit about yourself', max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_anonymous_preferred', models.BooleanField(default=True, help_text='Prefer anonymous interactions in community features')),
                ('allow_peer_matching', models.BooleanField(default=True, help_text='Allow matching with peers for support')),
                ('crisis_contact_phone', models.CharField(blank=True, help_text='Emergency contact number (optional)', max_length=20)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('last_mood_checkin', models.DateTimeField(blank=True, null=True)),
                ('notification_preferences', models.JSONField(default=dict, help_text='User notification preferences')),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('specializations', models.JSONField(default=list, help_text='Areas of mental health specialization')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When user was approved', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
            },
        ),
    ]
