# Generated by Django 5.1.7 on 2025-11-06 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('community_notifications', models.BooleanField(default=True)),
                ('assessment_reminders', models.BooleanField(default=True)),
                ('crisis_alerts', models.BooleanField(default=True)),
                ('guide_messages', models.BooleanField(default=True)),
                ('system_updates', models.BooleanField(default=True)),
                ('user_registration_notifications', models.BooleanField(default=True)),
                ('user_approval_notifications', models.BooleanField(default=True)),
                ('account_activation_notifications', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('community_reply', 'Community Reply'), ('community_like', 'Community Like'), ('assessment_reminder', 'Assessment Reminder'), ('crisis_alert', 'Crisis Alert'), ('peer_match', 'Peer Match'), ('guide_message', 'Guide Message'), ('system_update', 'System Update'), ('achievement', 'Achievement'), ('mood_checkin', 'Mood Check-in'), ('content_recommendation', 'Content Recommendation'), ('user_registration', 'User Registration'), ('user_approved', 'User Approved'), ('account_activated', 'Account Activated')], help_text='Type of notification', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of notification', max_length=10)),
                ('title', models.CharField(help_text='Notification title/headline', max_length=200)),
                ('message', models.TextField(help_text='Notification message body')),
                ('action_url', models.CharField(blank=True, help_text='Optional URL for notification action', max_length=500)),
                ('action_text', models.CharField(blank=True, help_text='Optional text for action button', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read the notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When notification was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration time for notification', null=True)),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
