# Generated by Django 5.1.7 on 2025-11-06 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time in seconds', null=True)),
                ('analysis_method', models.CharField(default='mock', help_text='AI service used', max_length=50)),
                ('total_captures', models.IntegerField(default=0)),
                ('successful_analyses', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_mood_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_analysis_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('neutral', 'Neutral'), ('fear', 'Fear'), ('disgust', 'Disgust')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score between 0 and 1', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('emotions_breakdown', models.JSONField(default=dict, help_text='Breakdown of all emotions with scores')),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'db_table': 'mood_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Recognition'), ('trend', 'Trend Analysis'), ('recommendation', 'Recommendation'), ('alert', 'Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(help_text='Confidence in this insight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_entries', models.ManyToManyField(blank=True, to='mood.moodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dominant_emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('neutral', 'Neutral'), ('fear', 'Fear'), ('disgust', 'Disgust')], max_length=20)),
                ('average_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('total_entries', models.IntegerField(default=0)),
                ('emotion_distribution', models.JSONField(default=dict, help_text='Distribution of emotions throughout the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_mood_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_trends',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
